[package]
name = "hook0-output-worker"
version = "0.3.0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2021"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook server", "events"]

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive", "env", "cargo", "wrap_help"] }
hex = "0.4.3"
hmac = "0.12.1"
itertools = "0.13.0"
log = "0.4.21"
reqwest = { version = "0.12.5", default-features = false, features = ["charset", "http2", "macos-system-configuration", "trust-dns", "json"] }
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.203"
serde_json = "1.0.118"
sha2 = "0.10.8"
sqlx = { version = "0.7.4", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "time", "json"] }
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros", "time"] }
uuid = { version = "1.9.1", features = ["v4"] }

[features]
default = ["reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots"]
