name: hook0

# Keycloak-related services/volumes were remove because Keycloak is no longer required by Hook0.
# If you have an instance that was created while Keycloak was required, use docker-compose-legacy-with-keycloak.yaml instead of this file.

volumes:
  postgres-data:
  mailpit-data:

services:
  postgres:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hook0
    ports:
      - "5432:5432"
    networks:
      - hook0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d $${POSTGRES_DB}"]
      timeout: 1s
      interval: 5s

  mailpit:
    image: axllent/mailpit:v1.19
    volumes:
      - mailpit-data:/data
    environment:
      - MP_DATABASE=/data/mailpit.db
      - POSTGRES_DB=hook0
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - hook0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider --user-agent 'docker-compose-healthcheck' http://localhost:8025/api/v1/info || exit 1"]
      timeout: 1s
      interval: 5s

  api:
    build:
      context: ../..
      dockerfile: self-hosted/docker/api.Dockerfile
    env_file: .env
    environment:
      - IP=0.0.0.0
      - PORT=8081
      - CORS_ALLOWED_ORIGINS=http://localhost:8001
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hook0
      - SMTP_CONNECTION_URL=smtp://mailpit:1025
      - EMAIL_SENDER_ADDRESS=sender@hook0.local
      - APP_URL=${APP_URL}
      - BISCUIT_PRIVATE_KEY=${BISCUIT_PRIVATE_KEY}
    ports:
      - "8081:8081"
    networks:
      - hook0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --user-agent 'docker-compose-healthcheck' http://localhost:$${PORT}/api/v1/swagger.json || exit 1"]
      timeout: 1s
      interval: 5s
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_healthy

  frontend:
    build:
      context: ../..
      dockerfile: self-hosted/docker/frontend.Dockerfile
    ports:
      - "8001:80"
    networks:
      - hook0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost || exit 1"]
      timeout: 1s
      interval: 5s
    depends_on:
      api:
        condition: service_healthy

  output-worker:
    build:
      context: ../..
      dockerfile: self-hosted/docker/output-worker.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hook0
      - WORKER_NAME=default
      - DISABLE_TARGET_IP_CHECK=true
    networks:
      - hook0
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy

networks:
  hook0:
    driver: bridge
